version: '3.8'

services:
     
  postgres:
    container_name: ch-postgres
    image: postgres
    ports:
      - 5432:5432
    environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    container_name: ch-redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["sh", "-c", "redis-server /usr/local/etc/redis/redis.conf --requirepass \"$REDIS_PASSWORD\""]

  localstack:
    container_name: ch-localstack
    image: "localstack/localstack:s3-latest"
    ports:
      - "4566-4584:4566-4584"
    environment:
      - DEBUG=${DEBUG:-0}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - EDGE_PORT=${EDGE_PORT:-4566}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
    volumes:
      - "./s3_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

