name: Test on Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests using npm script
        run: npm run test

  post-comment:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Post comment on pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = process.env['GITHUB_RUN_CONCLUSION'] === 'success' ? '✅ Tests passed!' : '❌ Tests failed.';
            const context = JSON.parse(process.env['GITHUB_CONTEXT']);
            const octokit = new github.getOctokit(process.env['GITHUB_TOKEN']);
            
            await octokit.rest.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: result,
            });
